### ISSUE TITLE
esptool.FatalError: MD5 of file does not match data in flash!

### ISSUE THREAD

**Issue by ttrueten** [filmanddarkroom/FADU_Timer#3]
Hi there,
I tried to flash a Sonoff S26R2. No Problems while flashing other firmwares like Tasmota etc. But with fadu.

```
Arduino: 1.8.13 (Linux), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Archiving built core (caching) in: /tmp/arduino_cache_237072/core/core_esp8266_esp8266_generic_xtal_80,vt_flash,exception_disabled,stacksmash_disabled,ssl_all,mmu_3232,non32xfer_fast,ResetMethod_nodemcu,CrystalFreq_26,FlashFreq_40,FlashMode_dout,eesz_1M64,led_2,sdk_nonosdk_190703,ip_lm2f,dbg_Disabled,lvl_None____,wipe_none,baud_115200_7de4efd70164a2718be3327b6fbdabbc.a
Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 269372          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27385   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1512  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1104  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26024 )         - zeroed variables      (global, static) in RAM/HEAP 
Der Sketch verwendet 299373 Bytes (31%) des Programmspeicherplatzes. Das Maximum sind 958448 Bytes.
Globale Variablen verwenden 28640 Bytes (34%) des dynamischen Speichers, 53280 Bytes für lokale Variablen verbleiben. Das Maximum sind 81920 Bytes.
esptool.py v3.0
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP8285
Features: WiFi, Embedded Flash
Crystal is 26MHz
MAC: 9c:9c:1f:89:d2:a3
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 303520 bytes to 220363...
Writing at 0x00000000... (7 %)
Writing at 0x00004000... (14 %)
Writing at 0x00008000... (21 %)
Writing at 0x0000c000... (28 %)
Writing at 0x00010000... (35 %)
Writing at 0x00014000... (42 %)
Writing at 0x00018000... (50 %)
Writing at 0x0001c000... (57 %)
Writing at 0x00020000... (64 %)
Writing at 0x00024000... (71 %)
Writing at 0x00028000... (78 %)
Writing at 0x0002c000... (85 %)
Writing at 0x00030000... (92 %)
Writing at 0x00034000... (100 %)
Traceback (most recent call last):
Wrote 303520 bytes (220363 compressed) at 0x00000000 in 19.4 seconds (effective 125.4 kbit/s)...
  File "/home/user/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/upload.py", line 66, in <module>
File  md5: 538d4ee7c29276668193d2280fb32ce7
Flash md5: 7e9950b68f9ded6fa5fea9bb0f7e6cea
    esptool.main(cmdline)
MD5 of 0xFF is c2be41b626cb606ebc04d1c8ad08e94f
  File "/home/user/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3604, in main
    operation_func(esp, args)
  File "/home/user/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3016, in write_flash
    raise FatalError("MD5 of file does not match data in flash!")
esptool.FatalError: MD5 of file does not match data in flash!
esptool.FatalError: MD5 of file does not match data in flash!
```

Any hints?

Cheers,
Thomas

**Comment by ttrueten** [comment]
After changing to another usb2ttl Adapter (homsun-ic.com) all is fine...
`(...)
Writing at 0x00034000... (100 %)
Wrote 303520 bytes (220363 compressed) at 0x00000000 in 19.4 seconds (effective 125.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...`

Cheers,
Thomas
